### ISSUE TITLE
error: IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by Light--** [skhadem/3D-BoundingBox#24]
$ python Run.py

output:
```
Traceback (most recent call last):
  File "Run.py", line 201, in <module>
    main()
  File "Run.py", line 137, in main
    detections = yolo.detect(yolo_img)
  File "code/3D-BoundingBox-master/yolo/yolo.py", line 34, in detect
    ln = [ln[i[0] - 1] for i in self.net.getUnconnectedOutLayers()]
  File "code/3D-BoundingBox-master/yolo/yolo.py", line 34, in <listcomp>
    ln = [ln[i[0] - 1] for i in self.net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.
```

**Comment by jmlbeaujour** [comment]
Replace: 
`ln = [ln[i[0] - 1] for i in self.net.getUnconnectedOutLayers()]` 
by
`ln = [ln[i - 1] for i in self.net.getUnconnectedOutLayers()]`

src: https://stackoverflow.com/questions/69834335/loading-yolo-invalid-index-to-scalar-variable
